# PA4, Sawyer Mason, V1, CS-150-01

In [10]:
import numpy as np

In [27]:
array=np.arange(10,41,10)
array1=array.reshape(2,2)

print(array1)
print()
print(array1**2)
print()
print(array1+100)
print()
print(array1*5)
print()
print(np.sqrt(array1))

[[10 20]
 [30 40]]

[[ 100  400]
 [ 900 1600]]

[[110 120]
 [130 140]]

[[ 50 100]
 [150 200]]

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [34]:
array2=np.arange(3,28,3)
array3=array2.reshape(3,3)
array4=np.linspace(10,21,9)
array5=array4.reshape(3,3)
array_sum=np.multiply(array5,array3)
print(array_sum)

[[ 30.    68.25 114.75]
 [169.5  232.5  303.75]
 [383.25 471.   567.  ]]


In [36]:
x1=np.load('process1.npy')
x2=np.load('process2.npy')
x3=np.load('process3.npy')
x4=np.load('process4.npy')
x5=np.load('process5.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'process1.npy'